server:
  port : 8081

general:
  message:  "hello world!"

spring:
  cloud:
    stream:
      bindings:
            input.destination: ignite-kafka-channel
            output.destination: ignite-kafka-channel
      kafka:
        binder:
            brokers: origin.os.local:9092
            minPartitionCount: 5
            autoAddPartitions: true

enableFilePersistence: true
igniteConnectorPort: 11211
igniteServerPortRange: 47500..47509
ignitePersistenceFilePath: d:\temp\data
initialDelay: 10000
fixedDelay: 60000      
cacheName: KafkaMessage