apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: ignite-kafka
  name: ignite-kafka
  namespace: ignite
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: ignite-kafka:0.0.1-SNAPSHOT
  postCommit: {
    }
  resources: {
    }
  runPolicy: Serial
  source:
    binary: {
      }
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.redhat.io/redhat-openjdk-18/openjdk18-openshift     
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers: [
    ]